### ISSUE TITLE
Text Concepts don't appear under Story Analysis

### ISSUE THREAD

**Issue by Sreyasi** [chengwill97/Story-and-Image-Alignment#85]
Sometimes Text Concepts doesn't appear under Story Analysis. We are probably pruning the text concepts to be displayed resulting in no concepts for some cases...need to check this.

**Comment by chengwill97** [comment]
Are you able to take a screenshot of this?

**Comment by Sreyasi** [comment]
![noTextTags2](https://user-images.githubusercontent.com/35703105/61131098-94dd9c80-a4b8-11e9-8d24-bd8bb1652fbd.JPG)
![noTextTags1](https://user-images.githubusercontent.com/35703105/61131099-94dd9c80-a4b8-11e9-8660-0f2813bb8473.JPG)
![aligned](https://user-images.githubusercontent.com/35703105/61131100-95763300-a4b8-11e9-8c0c-45155ed101f8.JPG)
