### ISSUE TITLE
Manual input for image tags

### ISSUE THREAD

**Issue by Sreyasi** [chengwill97/Story-and-Image-Alignment#90]
In the Story Analysis page, Top Concepts Alignments --> Image Tags, add a feature to add manual tags - "Not happy with detected tags? Enter your own."

This functionality already exists in the app as far as I remember - only gets triggered if no tags were automatically detected; now we just need to make it a click event.

**Comment by chengwill97** [comment]
Can you explain a little further? 

Do you want to make this page come up by default?

**Comment by Sreyasi** [comment]
After the images have been aligned with the paragraphs, we can go to the "Story Analysis" page to inspect the alignments, right? There we see the "Top Concepts" from paragraphs and images. I am proposing to add kind of a pop-up somewhere near where you display the image concepts. If our tools have detected the wrong concepts in the images, the users can enter their own concepts and have the alignment done once again. 

So, the pop-up can say something like "Not happy with detected tags? Enter your own.". On clicking that option, it takes the user to a page where they can enter tags for each image (you already have this page coded such that it would trigger when no tags are detected in images). At the end of this page we should have the "Make my story" button, so that the alignments can be recomputed based on user-entered tags.
